###
POST  http://localhost:3000/user/register
Content-Type: application/json 

{
    "name": "Haim",
    "phone":  596375,
    "email": "Haim@gmail.com",
    "password":  "Haim135624"
}

###
POST  http://localhost:3000/user/login
Content-Type: application/json 

{
    "name": "Haim",
    "phone":  596375,
    "email": "Haim@gmail.com",
    "password":  "Haim135624"
}

###
POST  http://localhost:3000/user/addFavorite
Content-Type: application/json 

{
    "email": "Haim@gmail.com",
    "mkt":"new3"
}

###
GET  http://localhost:3000/user/favorites
Content-Type: application/json 

{
   "email": "Haim@gmail.com"
}

###
POST  http://localhost:3000/user/removeFromFavorite
Content-Type: application/json 

{
    "email": "Haim@gmail.com",
    "mkt":"new3"
}
