###
POST  http://localhost:8081/user/register
Content-Type: application/json 

{
    "name": "mh",
    "phone":  82522,
    "email": "mh@gmail.com",
    "password":  "1"
}

# {
#     "name": "Haim",
#     "phone":  596375,
#     "email": "Haim@gmail.com",
#     "password":  "Haim135624"
# }

###
POST  http://localhost:8081/user/login
Content-Type: application/json 

{
    "name": "Haim",
    "phone":  596375,
    "email": "Haim@gmail.com",
    "password":  "Haim135624"
}

###
POST  http://localhost:8081/user/addFavorite
Content-Type: application/json 

{
    "email": "Haim@gmail.com",
    "mkt":"30027"
}

###
GET http://localhost:8081/user/favorites
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2FjMWRlYTFlY2JhYTg2M2Y4ZWFjMyIsInBob25lIjo1OTYzNzUsImVtYWlsIjoiSGFpbUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTYwODg3NiwiZXhwIjoxNzQxNjEyNDc2fQ.WVTRVUY7VHM7s8jQsnNxBHIkKvPPcgj-PNmiX9DXD-M;

{
   "email": "Haim@gmail.com"
}

# GET  http://localhost:8081/user/favorites
# Content-Type: application/json 

# {
#    "email": "Haim@gmail.com"
# }

###
POST  http://localhost:8081/user/removeFromFavorite
Content-Type: application/json 

{
    "email": "Haim@gmail.com",
    "mkt":"new3"
}

###
GET  http://localhost:8081/user/cart
Content-Type: application/json 

{
   "email": "eli2@gmail.com"
}


###
POST  http://localhost:8081/user/addToCart
Content-Type: application/json 

{
    "email": "eli2@gmail.com",
    "mkt":"new6"
}

###
POST  http://localhost:8081/user/removeFromCart
Content-Type: application/json 

{
    "email": "eli2@gmail.com",
    "mkt":"new6"
}