###
POST  http://localhost:3000/user/register
Content-Type: application/json 

{
    "name": "Mendy",
    "phone":  596375,
    "email": "mendy@gmail.com",
    "password":  "mendy12345"
}

###
POST  http://localhost:3000/user/login
Content-Type: application/json 

{
    "name": "eli2",
    "phone":  552884,
    "email": "eli2@gmail.com",
    "password":  "12345"
}


###
GET  http://localhost:3000/user/favorites
Content-Type: application/json 

{
   "email": "eli2@gmail.com"
}

###
POST  http://localhost:3000/user/addFavorite
Content-Type: application/json 

{
    "email": "eli2@gmail.com",
    "mkt":"new3"
}

###
POST  http://localhost:3000/user/addFavorite
Content-Type: application/json 

{
    "mkt":"new3"
}